const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:5173',{waitUntil:'networkidle'});
 await page.getByText('TRAINED ON YOUR DATASET · bulb-health-v1',{exact:true}).waitFor();
 await page.screenshot({path:'output/analysis-home-desktop.png',fullPage:true});
 await page.getByLabel('Upload file').setInputFiles('output/real-test-image.jpg');
 await page.getByRole('checkbox').check();
 await page.getByRole('button',{name:'Analyze image',exact:true}).click();
 const dialog=page.getByRole('dialog');
 await dialog.getByLabel('Password').fill(fs.readFileSync('data/local-demo-password.txt','utf8').trim());
 await dialog.getByRole('button',{name:'Sign in',exact:true}).click();
 await dialog.waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Analyze image',exact:true}).click();
 await page.getByRole('heading',{name:'Every onion, explained.'}).waitFor();
 await page.getByRole('button',{name:'Inspect onion 1'}).click();
 await page.getByText('Healthy bulb',{exact:true}).first().waitFor();
 await page.getByRole('button',{name:'Original',exact:true}).click();
 await page.getByRole('button',{name:'Annotated',exact:true}).click();
 const downloaded=page.waitForEvent('download');
 await page.getByRole('button',{name:'Generate report',exact:true}).click();
 await (await downloaded).saveAs('output/pdf/trained-health-browser-report.pdf');
 await page.screenshot({path:'output/trained-analysis-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'output/trained-analysis-mobile.png',fullPage:true});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile page overflow');
 await page.getByRole('button',{name:'New analysis',exact:true}).click();
 await page.getByLabel('Inference source').selectOption('demo');
 await page.getByLabel('Mock scenario').selectOption('multiple');
 await page.getByRole('button',{name:'Analyze image',exact:true}).click();
 await page.getByRole('button',{name:'Inspect onion 3'}).click();
 await page.getByRole('heading',{name:'Onion #3',exact:true}).waitFor();
 if(errors.length)throw Error(errors.join('\n'));
 console.log('PASS: trained model UI, login, real upload, clickable region, image toggle, PDF, mobile layout and mock per-onion selection');
 await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
