import {useEffect,useState} from 'react';
import type {Analysis,Point} from '../types';
import {imageUrl} from '../services/api';
export const colors:Record<string,string>={GOOD:'#67b981',DAMAGED:'#e6ad52',ROTTEN:'#e37772',SPROUTED:'#ad8bd5',UNDERSIZED:'#6caacb',REVIEW_REQUIRED:'#dab747'};
export function AnnotatedImage({result,selected,onSelect}:{result:Analysis;selected:number;onSelect:(id:number)=>void}){
 const [url,setUrl]=useState(''),[show,setShow]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let active=true;let loaded='';imageUrl(result.image_url).then(value=>{loaded=value;if(active)setUrl(value);else URL.revokeObjectURL(value);}).catch(e=>setError(e.message));return()=>{active=false;if(loaded)URL.revokeObjectURL(loaded);};},[result.id]);
 return <section className="card image-panel"><div className="section-title"><h3>Image evidence</h3><div className="segmented"><button className={!show?'chosen':''} onClick={()=>setShow(false)}>Original</button><button className={show?'chosen':''} onClick={()=>setShow(true)}>Annotated</button></div></div>{error&&<p className="error">{error}</p>}<div className="image-stage">{url&&<><img src={url} alt="Uploaded onion sample"/><svg viewBox={`0 0 ${result.width} ${result.height}`} aria-label="Clickable onion boundaries">{show&&result.detections.map(d=><g key={d.id} role="button" tabIndex={0} aria-label={`Inspect onion ${d.id}`} onClick={()=>onSelect(d.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(d.id);}}} style={{cursor:'pointer'}}>{d.mask?<polygon points={d.mask.map(p=>p.join(',')).join(' ')} fill={selected===d.id?colors[d.class]+'33':'transparent'} stroke={colors[d.class]} strokeWidth={selected===d.id?4:2} vectorEffect="non-scaling-stroke"/>:<rect x={d.bbox[0]} y={d.bbox[1]} width={d.bbox[2]-d.bbox[0]} height={d.bbox[3]-d.bbox[1]} fill="transparent" stroke={colors[d.class]} strokeWidth={3} vectorEffect="non-scaling-stroke"/>}<text x={d.bbox[0]+5} y={Math.max(25,d.bbox[1]-7)} fill="white" stroke="#1a3428" paintOrder="stroke" strokeWidth={3} fontSize={Math.max(16,result.width/38)} fontWeight="700">#{d.id}</text></g>)}</svg></>}</div><div className="image-caption">{result.demo?'Mock outlines do not identify the uploaded onions.':result.mode==='health'?'Regions are supplied by you. Health predictions come from the trained model.':'Model-generated instance boundaries.'} Select a boundary to inspect its finding.</div></section>
}
export function CalibrationCanvas({url,dimensions,points,polygon,regions,onPoint,tool}:{url:string;dimensions:Point;points:Point[];polygon:Point[];regions:Point[][];onPoint:(p:Point)=>void;tool:string}){
 return <div className={'image-stage editor '+(tool!=='none'?'drawing':'')}><img src={url} alt="Selected image for reference calibration and onion outlining"/><svg viewBox={`0 0 ${dimensions[0]} ${dimensions[1]}`} onClick={e=>{if(tool==='none')return;const rect=e.currentTarget.getBoundingClientRect();onPoint([Math.round((e.clientX-rect.left)/rect.width*dimensions[0]),Math.round((e.clientY-rect.top)/rect.height*dimensions[1])]);}}>{regions.map((r,i)=><polygon key={i} points={r.map(p=>p.join(',')).join(' ')} fill="#74b58122" stroke="#74b581" strokeWidth={2} vectorEffect="non-scaling-stroke"/>)}<polyline points={polygon.map(p=>p.join(',')).join(' ')} fill="none" stroke="#f6bf58" strokeWidth={2} vectorEffect="non-scaling-stroke"/>{[...polygon,...points].map((p,i)=><circle key={i} cx={p[0]} cy={p[1]} r={dimensions[0]/110} fill="#ffc564"/>)}{points.length===2&&<line x1={points[0][0]} y1={points[0][1]} x2={points[1][0]} y2={points[1][1]} stroke="#41c6e2" strokeWidth={3} vectorEffect="non-scaling-stroke"/>}</svg></div>
}
