import {ArrowRight,ShieldCheck} from 'lucide-react';

export type AuthView='signin'|'signup'|'verify';
export function LoginScreen({view,onView,onHome,email,onEmail,password,onPassword,name,onName,code,onCode,onSubmit,onResend,onDemo,busy,error,message}:{view:AuthView;onView:(value:AuthView)=>void;onHome:()=>void;email:string;onEmail:(value:string)=>void;password:string;onPassword:(value:string)=>void;name:string;onName:(value:string)=>void;code:string;onCode:(value:string)=>void;onSubmit:()=>void;onResend:()=>void;onDemo:()=>void;busy:boolean;error:string;message:string}){
 const signingUp=view==='signup',verifying=view==='verify';
 return <div className="login-screen"><div className="login-visual"><button className="login-brand" onClick={onHome} aria-label="Visionion public home"><span className="onion-mark">◉</span> Visionion</button><div className="login-message"><span className="eyebrow">ONION QUALITY INTELLIGENCE</span><h1>Intelligence meets<br/><em>the harvest.</em></h1><p>Image-backed quality evidence for clearer onion inspections.</p><div className="login-proof"><span><ShieldCheck size={18}/> Trained on your onion dataset</span><span>Every finding stays traceable</span></div></div></div>
  <div className="login-form-pane"><div className="login-form-wrap"><span className="eyebrow">YOUR VISIONION ACCOUNT</span><h2>{verifying?'Verify your email':signingUp?'Create an account':'Welcome back'}</h2><p>{verifying?`Enter the six-digit code sent to the inbox for ${email}. Check your Gmail app and spam folder. It expires in 10 minutes.`:signingUp?'Sign up to save inspections and reports. Your code will arrive by email, including in the mail app on your phone.':'Sign in to inspect images and access saved reports.'}</p><form onSubmit={event=>{event.preventDefault();onSubmit();}}>{signingUp&&<label>FULL NAME<input autoComplete="name" value={name} onChange={event=>onName(event.target.value)} required/></label>}{!verifying&&<><label>EMAIL ADDRESS<input type="email" autoComplete="email" value={email} onChange={event=>onEmail(event.target.value)} placeholder="you@example.com" required/></label><label>PASSWORD<input type="password" autoComplete={signingUp?'new-password':'current-password'} minLength={signingUp?10:undefined} value={password} onChange={event=>onPassword(event.target.value)} placeholder={signingUp?'At least 10 characters':'Enter your password'} required/></label></>}{verifying&&<label>VERIFICATION CODE<input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" value={code} onChange={event=>onCode(event.target.value.replace(/\D/g,''))} placeholder="000000" required/></label>}{error&&<p role="alert" className="login-error">{error}</p>}{message&&<p role="status" className="login-success">{message}</p>}<button className="primary login-submit" disabled={busy}>{busy?'Please wait…':verifying?'Verify email':signingUp?'Send verification code':'Sign in to Visionion'} <ArrowRight size={17}/></button></form>{!verifying&&<div className="demo-signin"><button type="button" className="secondary login-submit" onClick={onDemo} disabled={busy}>Try demo <ArrowRight size={17}/></button><p>No email or OTP needed. Explore inspections and reports in your own one-hour session. Download reports before signing out; a new demo starts with an empty history.</p></div>}<div className="auth-switch">{verifying?<><button onClick={onResend} disabled={busy}>Resend code</button><button onClick={()=>onView('signin')}>Already verified? Sign in</button></>:<button onClick={()=>onView(signingUp?'signin':'signup')}>{signingUp?'Already have an account? Sign in':'New here? Create an account'}</button>}</div><small>Research prototype · No government certification</small></div></div>
 </div>;
}
